import type { Page, WebsiteMetadata } from "../types";

/**
 * Convert pages to HTML format with metadata
 */
export function formatToHTML(
  pages: Page[],
  baseUrl: string,
  scrapedAt: string,
  duration: number,
  website: WebsiteMetadata
): string {
  const html = `<!DOCTYPE html>
<html lang="${website.language || "en"}">
<head>
    <meta charset="${website.charset || "UTF-8"}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrape: ${website.title || extractDomainFromUrl(baseUrl)}</title>
    ${generateMetaTags(website)}
    <style>
        ${generateCSS()}
    </style>
</head>
<body>
    <header class="header">
        <h1>Website Scrape: ${escapeHtml(website.title || extractDomainFromUrl(baseUrl))}</h1>
        <div class="meta-info">
            <p><strong>Base URL:</strong> <a href="${escapeHtml(
              baseUrl
            )}" target="_blank">${escapeHtml(baseUrl)}</a></p>
            <p><strong>Scraped at:</strong> ${new Date(scrapedAt).toLocaleString()}</p>
            <p><strong>Duration:</strong> ${duration}ms</p>
            <p><strong>Total pages:</strong> ${pages.length}</p>
            ${
              website.description
                ? `<p><strong>Description:</strong> ${escapeHtml(website.description)}</p>`
                : ""
            }
            ${website.author ? `<p><strong>Author:</strong> ${escapeHtml(website.author)}</p>` : ""}
            ${
              website.language
                ? `<p><strong>Language:</strong> ${escapeHtml(website.language)}</p>`
                : ""
            }
        </div>
    </header>

    ${pages.length > 1 ? generateTOC(pages) : ""}

    <main class="content">
        ${pages.map((page, index) => generatePageHTML(page, index + 1)).join("\n")}
    </main>

    <footer class="footer">
        <p>Generated by Reader JS/TS SDK</p>
    </footer>

    <script>
        ${generateJavaScript()}
    </script>
</body>
</html>`;

  return html;
}

/**
 * Generate meta tags for HTML head
 */
function generateMetaTags(website: WebsiteMetadata): string {
  const tags: string[] = [];

  if (website.description) {
    tags.push(`<meta name="description" content="${escapeHtml(website.description)}">`);
  }

  if (website.author) {
    tags.push(`<meta name="author" content="${escapeHtml(website.author)}">`);
  }

  if (website.keywords) {
    tags.push(`<meta name="keywords" content="${escapeHtml(website.keywords.join(", "))}">`);
  }

  if (website.robots) {
    tags.push(`<meta name="robots" content="${escapeHtml(website.robots)}">`);
  }

  if (website.themeColor) {
    tags.push(`<meta name="theme-color" content="${escapeHtml(website.themeColor)}">`);
  }

  if (website.favicon) {
    tags.push(`<link rel="icon" href="${escapeHtml(website.favicon)}">`);
  }

  if (website.canonical) {
    tags.push(`<link rel="canonical" href="${escapeHtml(website.canonical)}">`);
  }

  // Open Graph tags
  if (website.openGraph) {
    const og = website.openGraph;
    if (og.title) tags.push(`<meta property="og:title" content="${escapeHtml(og.title)}">`);
    if (og.description)
      tags.push(`<meta property="og:description" content="${escapeHtml(og.description)}">`);
    if (og.type) tags.push(`<meta property="og:type" content="${escapeHtml(og.type)}">`);
    if (og.url) tags.push(`<meta property="og:url" content="${escapeHtml(og.url)}">`);
    if (og.image) tags.push(`<meta property="og:image" content="${escapeHtml(og.image)}">`);
    if (og.siteName)
      tags.push(`<meta property="og:site_name" content="${escapeHtml(og.siteName)}">`);
    if (og.locale) tags.push(`<meta property="og:locale" content="${escapeHtml(og.locale)}">`);
  }

  // Twitter Card tags
  if (website.twitter) {
    const twitter = website.twitter;
    if (twitter.card) tags.push(`<meta name="twitter:card" content="${escapeHtml(twitter.card)}">`);
    if (twitter.site) tags.push(`<meta name="twitter:site" content="${escapeHtml(twitter.site)}">`);
    if (twitter.creator)
      tags.push(`<meta name="twitter:creator" content="${escapeHtml(twitter.creator)}">`);
    if (twitter.title)
      tags.push(`<meta name="twitter:title" content="${escapeHtml(twitter.title)}">`);
    if (twitter.description)
      tags.push(`<meta name="twitter:description" content="${escapeHtml(twitter.description)}">`);
    if (twitter.image)
      tags.push(`<meta name="twitter:image" content="${escapeHtml(twitter.image)}">`);
  }

  return tags.join("\n    ");
}

/**
 * Generate CSS styles for the HTML output
 */
function generateCSS(): string {
  return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f8f9fa;
        }

        .header {
            background: white;
            padding: 2rem;
            border-bottom: 1px solid #e9ecef;
            margin-bottom: 2rem;
        }

        .header h1 {
            color: #2c3e50;
            margin-bottom: 1rem;
            font-size: 2rem;
        }

        .meta-info {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 0.5rem;
        }

        .meta-info p {
            margin: 0.25rem 0;
            font-size: 0.9rem;
            color: #6c757d;
        }

        .toc {
            background: white;
            padding: 1.5rem;
            margin: 2rem 0;
            border-radius: 8px;
            border: 1px solid #e9ecef;
        }

        .toc h2 {
            color: #2c3e50;
            margin-bottom: 1rem;
            font-size: 1.25rem;
        }

        .toc ul {
            list-style: none;
        }

        .toc li {
            margin: 0.5rem 0;
        }

        .toc a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.2s;
        }

        .toc a:hover {
            color: #0056b3;
            text-decoration: underline;
        }

        .content {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 1rem;
        }

        .page {
            background: white;
            margin: 2rem 0;
            padding: 2rem;
            border-radius: 8px;
            border: 1px solid #e9ecef;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }

        .page-header {
            border-bottom: 2px solid #e9ecef;
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }

        .page-header h2 {
            color: #2c3e50;
            margin-bottom: 0.5rem;
            font-size: 1.5rem;
        }

        .page-meta {
            display: flex;
            flex-wrap: wrap;
            gap: 1rem;
            font-size: 0.9rem;
            color: #6c757d;
        }

        .page-content {
            line-height: 1.8;
        }

        .page-content h1, .page-content h2, .page-content h3,
        .page-content h4, .page-content h5, .page-content h6 {
            color: #2c3e50;
            margin: 1.5rem 0 0.5rem 0;
        }

        .page-content p {
            margin: 1rem 0;
        }

        .page-content a {
            color: #007bff;
            text-decoration: none;
        }

        .page-content a:hover {
            text-decoration: underline;
        }

        .page-content code {
            background: #f8f9fa;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            font-size: 0.9em;
        }

        .page-content pre {
            background: #f8f9fa;
            padding: 1rem;
            border-radius: 4px;
            overflow-x: auto;
            margin: 1rem 0;
        }

        .page-content blockquote {
            border-left: 4px solid #007bff;
            padding-left: 1rem;
            margin: 1rem 0;
            color: #6c757d;
        }

        .footer {
            text-align: center;
            padding: 2rem;
            margin-top: 3rem;
            border-top: 1px solid #e9ecef;
            color: #6c757d;
            font-size: 0.9rem;
        }

        @media (max-width: 768px) {
            .header {
                padding: 1rem;
            }

            .header h1 {
                font-size: 1.5rem;
            }

            .page {
                padding: 1rem;
            }

            .page-meta {
                flex-direction: column;
                gap: 0.5rem;
            }
        }
    `.trim();
}

/**
 * Generate table of contents HTML
 */
function generateTOC(pages: Page[]): string {
  const tocItems = pages
    .map((page, index) => {
      const pageNumber = index + 1;
      const title = page.title || `Page ${pageNumber}`;
      const id = `page-${pageNumber}`;
      return `<li><a href="#${id}">${pageNumber}. ${escapeHtml(title)}</a></li>`;
    })
    .join("\n");

  return `
    <nav class="toc">
        <h2>Table of Contents</h2>
        <ul>
            ${tocItems}
        </ul>
    </nav>`;
}

/**
 * Generate individual page HTML
 */
function generatePageHTML(page: Page, pageNumber: number): string {
  const id = `page-${pageNumber}`;
  const title = page.title || `Page ${pageNumber}`;

  return `
    <article class="page" id="${id}">
        <div class="page-header">
            <h2>${pageNumber}. ${escapeHtml(title)}</h2>
            <div class="page-meta">
                <span><strong>URL:</strong> <a href="${escapeHtml(
                  page.url
                )}" target="_blank">${escapeHtml(page.url)}</a></span>
                <span><strong>Depth:</strong> ${page.depth}</span>
                <span><strong>Fetched:</strong> ${new Date(page.fetchedAt).toLocaleString()}</span>
            </div>
        </div>
        <div class="page-content">
            ${page.html}
        </div>
    </article>`;
}

/**
 * Generate JavaScript for interactive features
 */
function generateJavaScript(): string {
  return `
        // Smooth scrolling for TOC links
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });

        // Highlight current section in TOC
        window.addEventListener('scroll', function() {
            const pages = document.querySelectorAll('.page');
            const tocLinks = document.querySelectorAll('.toc a');
            
            let currentPage = null;
            pages.forEach(page => {
                const rect = page.getBoundingClientRect();
                if (rect.top <= 100) {
                    currentPage = page;
                }
            });

            tocLinks.forEach(link => {
                link.style.fontWeight = 'normal';
                const target = document.querySelector(link.getAttribute('href'));
                if (target === currentPage) {
                    link.style.fontWeight = 'bold';
                }
            });
        });
    `;
}

/**
 * Escape HTML characters to prevent XSS
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&")
    .replace(/</g, "<")
    .replace(/>/g, ">")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;")
    .replace(/\//g, "&#x2F;");
}

/**
 * Extract domain from URL for fallback title
 */
function extractDomainFromUrl(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return "Unknown";
  }
}

/**
 * Generate a print-friendly version
 */
export function formatToPrintHTML(
  pages: Page[],
  baseUrl: string,
  scrapedAt: string,
  website: WebsiteMetadata
): string {
  const printStyles = `
        @media print {
            .header, .toc, .footer {
                display: none;
            }
            
            .page {
                page-break-after: always;
                box-shadow: none;
                border: none;
                margin: 0;
                padding: 0;
            }
            
            body {
                background: white;
                font-size: 12pt;
            }
        }
    `;

  return formatToHTML(pages, baseUrl, scrapedAt, 0, website).replace(
    "</style>",
    `${printStyles}\n        </style>`
  );
}
